#!/usr/bin/php
<?php

/**
 * This file is basically your development bootstrap/stub
 * You'd use the file to access your application while in development.
 * it requires the boot.php and your main entry file (main.php)
 * 
 * Also it is an executable so you could just use
 *      $ ./makephp
 * to access your app in development
 * 
 */

/* The constant IS_BUILD is populated in the build bootstrap (by default: ./build/bootstrap.php) */
/* In development this will never be defined, so lets define it now */
define('IS_BUILD', false);
/* Also a bunch of build constants will never be defined, so lets have that here */
define('BUILD_ID', uniqid('DEV'));
define('BUILD_TIME', time());
define('BUILD_NUMBER', 0);

/* Lets get some more errors while we're in development */
error_reporting(E_ALL);
@ini_set('display_errors', 'On');


/* Require the boot script */
if(file_exists('boot.php')) {
    require 'boot.php';
}
/* Require the main php entry file */
require 'main.php';

